# Downloader settings
url: "https://www.football-data.co.uk/downloadm.php"
file_name: "Season 2024/2025" # File name on the website
sheets_mapping:
  { "E0": "england-premier-league", "SC0": "scotland-premiership" }
fill_columns: { "B365H": "BWH", "B365D": "BWD", "B365A": "BWA" } # To from columns which to fill N/A values
save_dir: "outputs" # Where to save outputs
# Ingestor settings
league: "E0"
features: ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR", "HTHG", "HTAG", "HTR", "HS", "AS", "HST", "AST", "AvgH", "AvgD", "AvgA", "Avg>2.5", "Avg<2.5"]